### ISSUE TITLE
Command prefixes and you

### ISSUE THREAD

**Issue by Delra** [luuknieuwdorp/community-queues#11]
From a quick revelation I shared on this discord: 
`I just got slapped in the face by a revelation
Why the heck is the convention for discord bots a message prefix (like !command) and not @mybot command ????
@mybot is inherently unique and will never have conflict with another bot`

Do we want to move to using this convention, or will it be too frustrating? @luuknieuwdorp raised concerns that maybe it will be too cumbersome, but in reality `@que[enter] <command> <args>` is probably all it would require, and that's not too bad at all.

**Comment by ellienieuwdorp** [comment]
I think it's twofold, kinda cumbersome to actually type @que.... everytime and it'll clutter up the chat too making it less clean and harder to read. It's not a big deal but as long as we don't have any conflicts I think the current solution is more elegant.

**Comment by ellienieuwdorp** [comment]
Automatically implemented because of the switch to commando.
