### ISSUE TITLE
Bot fills up 1st team beyond 3 people

### ISSUE THREAD

**Issue by CodingRays** [luuknieuwdorp/community-queues#17]
See attached picture
![SharedScreenshot](https://user-images.githubusercontent.com/3766898/104212767-dc3e4380-5435-11eb-898a-43e6f097a3b7.png)

**Comment by ellienieuwdorp** [comment]
It broke when there was about 18 people. Not too familiar with testing in js but I think it would be a very good idea to write an automated test with the distribute code that simulates and actual use case scenario (e.g. 15+ people).
