### ISSUE TITLE
Redesign of PlayerQueue/CaptainQueue dynamic

### ISSUE THREAD

**Issue by CodingRays** [luuknieuwdorp/community-queues#21]
I think the current implementation of captains get added before players has some problems.
There have been 2 issues of note here.
1) Since we need to check for captains that are in the player list and vice versa (see #18 ) there arrives the issue of what do we do when we add/remove a captain that was a player before. The adding is easy we just remove them from the player list. But if on the other hand  we remove a captain that was a player before we would need to keep his previous place stored if we wanted to move that player back into the queue. There is also the question of captains that want to leave but cant remove themselves from the captain list. 
2) It was both confusing for consumers as well as more cumbersome than it could've been for administrators when you first had to add the captains during which people couldnt join. In particular counting seems to have been an unnecessary issue.

My proposal is to change the dynamic so that everyone first has to join the player list. From that pool of players admins can then select a set of captains or have the bot autoselect. Those captains are not removed from the player list but only marked. The big advantage here is that there is a single list that defines who is participating in the games and that is the player list. (captains can still be added to a separate list for easy iteration but they always remain in the player list). This massively simplifies list management and therefore reduces the potential for bugs as well as solving the previously stated issues.
1) When adding a captain there are no checks needed. When removing a captain the mark is simply removed and he remains in the player list. When a captain wants to leave he can easily do that with the standard command.
2) It is probably a more intuitive approach and eliminates the need for counting up players before selecting the captain and letting anyone join.

**Comment by ellienieuwdorp** [comment]
Great idea, I spoke with Nihil about this and it would also be nice to not *have* to select a captain for every team. If there are players left but not captains when distributing we should just do the remaining teams totally randomly out of remaining players.
