### ISSUE TITLE
Coding standards?

### ISSUE THREAD

**Issue by CodingRays** [luuknieuwdorp/community-queues#4]
I was wondering about coding conventions that should be used for this project.
Is there any convention were supposed to follow?

**Comment by ellienieuwdorp** [comment]
As for styling, I was thinking of adding https://prettier.io to enforce a common style.
As for naming, I just kinda assumed camelCase and it seems like Delra did the same. Seems like this is common in JS so I say we keep it.

If you have any ideas for things that do not fall under these please suggest them.

**Comment by CodingRays** [comment]
That sounds sensible to me. What i still wonder about is comment structure for documentation.

If we want to be really lazy we can just adopt a proven convention. What i usually do in my c++ projects is use the google coding conventions. https://google.github.io/styleguide/jsguide.html

But id refer to @Delra for this one since he has a lot more experience with this

**Comment by Delra** [comment]
I'm a fan of the google style guide, personally! It's very concise and excellent, not to mention we're basically just talking about clang-format.

**Comment by Delra** [comment]
Also, re: styling, I prefer camelCase but was actually doing my best to stick to a similar style to what you already had lol

**Comment by ellienieuwdorp** [comment]
Let's agree to google coding conventions then :)
