### ISSUE TITLE
Distributing and displaying teams

### ISSUE THREAD

**Issue by ellienieuwdorp** [luuknieuwdorp/community-queues#8]
After captains and players have been added, teams must be distributed randomly. We need to ensure teams are balanced. 
F.e: Rather 2 trios and 2 duos rather than 3 trios and 1 solo captain.
Consider this issue a place for discussions about how to solve this problem ;-)

After distributing, the teams should be displayed. I have not researched this much but know discord supports markdown to some degree. Possibly a markdown table?

**Comment by CodingRays** [comment]
Also we somehow have to handle the cases where we have too many captains or to few captains.

The first might seem simple since we can just distribute to have teams with 2 captains and only make one of them the real captain. But i think that opens up the possibility that we suddenly have 2 masters on a team where we could instead have 2 teams with one master and a diamond. Ie the exact situation we wanted to avoid in the first place.
For this reason i think it might be better to ditch the preset captains entirely and instead have the mods set the ranks for discord members that are of diamond or higher. The bot then looks at all people in the queue and distributes them according to that rank with the highest rank becoming team captain. This would also reduce the effort needed to setup the games since the mods only have to set the rank once and the bot can remember them for all future sessions.

**Comment by Delra** [comment]
To solve the issue of team distribution, I would do a random slice to each captain in order; then if there's any left in the team table, do it again, to a max of 2 players in each captain until there are no more teams with less than three players or there are no more players to distribute. This should produce a list as-even-as-possible. This is an easy solution if we stay with the current design... 

@CodingRays I like your idea by concept but it does massively complicate the situation if we are going to go all the way with that implementation; we'd have to create a weighted system by rank and seek to not let a team exceed a certain weight and also seek to keep a team above a minimum weight.

**Comment by CodingRays** [comment]
@Delra I dont think it would be that difficult. We know the number of teams based on the amount of players in the queue. From there we can start to distribute first the highest ranked players then the next highest rank etc. This is simple and im fairly certain would lead to a close to optimal solution.

**Comment by CodingRays** [comment]
Also i think that if we stay with the current design then Delras solutions would be a reasonable pick.

**Comment by CodingRays** [comment]
To further expand on my solution. I dont think its necessary to do any fancy weighting functions. The main goal here is to avoid having 2 predators or masters on the same team. We dont need perfect balance just reasonable balance. The the proposed solution does that while also making it easier to setup games.

**Comment by Delra** [comment]
Oh, okay, I see what you're saying. That's fine, but what if someone doesn't want to be a captain? Will they be able to flag themselves exclusionary to that, or will it be forced?
ETA: "forced" as in, by joining the queue, you have to accept that you might become a team captain. Get over it!

**Comment by CodingRays** [comment]
Well as far as i know captain shouldn't really mean anything. Its just the person that queues up nothing more. Or at least that what Dan said captains should be. I'm pretty sure we had a lengthy discussion about this on discord at some point.

Considering this maybe we should actually rename captain to something that's more reminiscent of what they actually have to do. I do agree that calling someone captain might put pressure on them.

**Comment by Delra** [comment]
I see, I see; I was thinking "captain = IGL", so... yeah. Haha. I don't know what else we'd call it though, if all they're doing is connecting to London.

**Comment by CodingRays** [comment]
Yeah it should be something simple that cant be misunderstood...
"Queue chief" idk lol

Maybe we should ask this question in the discord. This seems like a community question not a programming question. @luuknieuwdorp youre a mod maybe you should look into this.

**Comment by CodingRays** [comment]
As for displaying i think the markdown table is a good idea. Wouldn't know any better solution really.

**Comment by ellienieuwdorp** [comment]
After some discussion and consideration we'd think it'd be best to go with Delra's simpler solution. 

While Rays's use case is valid and somewhat likely, the main goal of the bot regarding skill gaps is making sure plat and below players have at least someone with decent mechanics/experience against the other teams, not to try and achieve statistical balance across every single team.

Moreover, currently we don't actually have any masters players participating in the queue's and stacking to some degree will be hard to avoid.

Another point considered is that for various reasons the discord server shies away from adding rank roles that are not Masters.

Lastly, even though that solution is not exponentially more complicated, it would still require significantly more work while we are already pretty close to an MVP ready for a test run.

Another small note, while a markdown table is definitely a nice to have, this will introduce more development time while something like [this](https://x.nieuwdorp.me/Yemi8/HEneCiHe34.png) will work perfectly fine for an MVP :)

**Comment by Delra** [comment]
Okay, cool. I was just checking to see if there was an answer so I could move forward on this. Once we have a mvp, we will move on: autodistributing teams into vcs (we'll need 20 Team vcs total) and a prettier markdown table. For now we will use the example linked and move on (primarily using their name)... though honestly if I realized we were not going to use `@person` in the first place I would have just saved the person's name, haha

**Comment by Delra** [comment]
For coding: are you alright with using a Map to Map team captains to an array of players?

**Comment by Delra** [comment]
getting a user's nickname in a given guild is a gigantic PITA. For now I'll just use their .tag...

**Comment by CodingRays** [comment]
@Delra Thats what i was thinking as well. I don't see any reason to use something else.

**Comment by CodingRays** [comment]
@luuknieuwdorp Did you ask about the renaming of the captain role?

**Comment by ellienieuwdorp** [comment]
Bumping this as we need to look at it again, it broke when there was about 18 people. team 1 had 6 members and last two teams only had captains.
Not familiar with testing but I think it would be a very good idea to write an automated test with the distribute code that simulates and actual use case scenario (e.g. 15+ people).
